
<div style="width:100%;text-align:center;">
<div style="width:900px;margin:auto;">
 <video width="900" controls>
  <source src="https://api.poleterresolide.fr/video/test-video.mp4" type="video/mp4">
  <source src="https://api.poleterresolide.fr/video/test-video.ogv" type="video/ogg">
   <source src="https://api.poleterresolide.fr/video/test-video.webm" type="video/webm">
  Your browser does not support the video tag.
</video>
</div>
</div> 