
<div style="width:100%;text-align:center;">
<div style="width:900px;margin:auto;">
 <video width="900" controls poster="https://api.poleterresolide.fr/video/formater-in-action.png">
  <source src="https://api.poleterresolide.fr/video/formater-in-action2.mp4" type="video/mp4">
  <source src="https://api.poleterresolide.fr/video/formater-in-action2.ogv" type="video/ogg">
   <source src="https://api.poleterresolide.fr/video/formater-in-action2.webm" type="video/webm">
  Your browser does not support the video tag.
</video>
</div>
</div> 
