
<div style="width:80%;margin:auto;height:600px;">

<formater-geotiff-serie id="test" metadataurl="https://api.poleterresolide.fr/geotiff/mexico/info_ft4.json" lang="<?=$lang?>"></formater-geotiff-serie>

</div>
<!-- The file is generated when we laucnch in console: npm run pre
then push on github branch master
Modify the url according to your own configuration -->

<script src="https://api.poleterresolide.fr/webcomponents/formater-geotiff-serie-vjs_0.5.1.js"></script> 
