

<geotiff-visualizer jsonurl='https://api.poleterresolide.fr/geotiff/vatican/list-vatican.json' lang="<?=$lang?>"></geotiff-visualizer>
 <!--  -<formater-map id="test" metadataurl="http://api.formater/geotiff/mexico/info_ft2.json"></formater-map> -->
	 
 <script type="text/javascript">
    window.onbeforeunload = function () {
    	  window.scrollTo(0, 0);
    	}
 </script>

  <script src="https://api.poleterresolide.fr/webcomponents/formater-geotiff-visualizer-vjs_0.0.2.js"></script> 
