 <div class="partenaire" style="text-align:center">
 <div>
 	<a href="http://www.cnrs.fr/" target="_blank"  title="CNRS">
 	 <img alt="CNRS"  style="max-width: 100%;" sizes="(max-width: 40px) 100vw, 40px" src="<?=IMAGES_URL?>/200px-CNRS.svg.png" width="40" height="40">
 	</a>
 </div>
 <div>
 	<a href="https://cnes.fr/fr" target="_blank"  title="CNES">
 	<img alt="CNES" class="attachment-logo-partenaire" style="max-width: 100%;" src="<?=IMAGES_URL?>/cnes_logo_essai-100x33-100x33.png" width="100" height="33">
 	</a> 
  </div>
 <div>
 <a href="http://www.ipgp.fr/fr" target="_blank" title="IPGP">
   <img alt="IPGP" style="max-width: 100%;"  sizes="(max-width: 45px) 100vw, 45px" src="<?=IMAGES_URL?>/logo-ipgp-transparent.png" width="45" height="50">
   </a>
 </div>
</div>