 <div class="partenaire" style="text-align:center">
 <div>
 	<a href="http://www.cnrs.fr/" target="_blank"  title="CNRS">
 	 <img alt="CNRS"  style="max-width: 100%;" sizes="(max-width: 40px) 100vw, 40px" src="<?=IMAGES_URL?>/200px-CNRS.svg.png" width="40" height="40">
 	</a>
 </div>
 <div>
 	<a href="https://cnes.fr/fr" target="_blank"  title="Centre National d'Etudes Spatiales">
 	<img alt="Centre National d'Etudes Spatiales" class="attachment-logo-partenaire" style="max-width: 100%;" src="<?=IMAGES_URL?>/cnes_logo_essai-100x33-100x33.png" width="100" height="33">
 	</a> 
  </div>
 <div>
 <a href="http://www.ipgp.fr/fr" target="_blank" title="Institut de Physique du Globe de Paris">
   <img alt="Institut de Physique du Globe de Paris" style="max-width: 100%;"  sizes="(max-width: 45px) 100vw, 45px" src="<?=IMAGES_URL?>/logo-ipgp-transparent.png" width="45" height="50">
   </a>
 </div>
 <div>
 <a href="https://www.epos-ip.org/" target="_blank" title="European Plate Observing System">
   <img alt="European Plate Observing System" style="max-width: 100%;"  sizes="(max-width: 45px) 100vw, 45px" src="<?=IMAGES_URL?>/epos.png" height="45">
   </a>
 </div>
  <div>
 <a href="http://www.ign.fr/" target="_blank" title="IGN">
   <img alt="IGN" style="max-width: 100%;"  sizes="(max-width: 45px) 100vw, 45px" src="<?=IMAGES_URL?>/IGN.png" height="60">
   </a>
 </div>
 <div>
 <a href="https://isterre.fr/" target="_blank" title="ISTerre">
   <img alt="ISTerre" style="max-width: 100%;"  sizes="(max-width: 45px) 100vw, 45px" src="<?=IMAGES_URL?>/logo_isterre.png" height="55">
   </a>
 </div>
 <div>
 <a href="http://www.osug.fr/" target="_blank" title="Observatoire des Sciences de l'Univers de Grenoble">
   <img alt="Observatoire des Sciences de l'Univers de Grenoble" style="max-width: 100%;"  sizes="(max-width: 45px) 100vw, 45px" src="<?=IMAGES_URL?>/logo_osug.png" height="55">
   </a>
 </div>
 <div>
 <a href="https://www.univ-grenoble-alpes.fr/" target="_blank" title="Université Grenoble Alpes">
   <img alt="Université Grenoble Alpes" style="max-width: 100%;"  sizes="(max-width: 45px) 100vw, 45px" src="<?=IMAGES_URL?>/logo-uga.png" height="55">
   </a>
 </div>
 <div>
 <a href="http://www.sorbonne-paris-cite.fr/" target="_blank" title="Université Sorbonne Paris Cité">
   <img alt="Université Sorbonne Paris Cité" style="max-width: 100%;"  sizes="(max-width: 45px) 100vw, 45px" src="<?=IMAGES_URL?>/logo-uspc.png" height="55">
   </a>
 </div>
</div>