 <?php 


 ?>
 
 <div>
   <?php if(isset($home)):?>
   <a href="<?php printer('url_new');?>" target="_blank">
     <img src="<?=IMAGES_URL?>/logo-formater-transparent.png" style="max-height: 95%;height:70px;margin-top:10px;"/>
   </a>
   <?php else: ?>
    <a href="<?=APP_URL?>?lang=<?=$lang?>">
     <img src="<?=IMAGES_URL?>/logo-formater-transparent.png" style="max-height: 95%;height:70px;margin-top:10px;"/>
   </a>
   <?php endif;?>
   <a href="https://www.etalab.gouv.fr/" target="_blank">
     <img src="<?=IMAGES_URL?>/logo-etalab-recentre.png" style="margin-left:30px;max-height: 95%;height:70px;margin-top:10px;"/>
   </a>
</div>
<div style="float:right">
 <ul>
  <li>
    <a href="<?php printer('url_etalab_on_formater')?>" target="_blank"><?php printer('etalab_on_formater')?></a>
  </li>
  <!-- demos -->
  <li class="menu-demo" style="min-width:200px;">
   <a id ="#demonstration" href="#demonstration">
       <span style="margin-left:0.3em;"><?php printer('demonstration');?></span>
    </a>
    <ul class="sub-menu">
   <?php foreach($data->demonstrations as $index => $demonstration):?>
    <li>
       <?php if (isset($article_index) && $article_index === $index): ?>
       <span style="opacity:0.6"><?=$demonstration->title->{$lang}?></span>
       <?php else:?>
       <a href="<?=$demonstration->url?>?lang=<?=$lang?>" title="<?=$demonstration->title->{$lang}?>">
       <?=$demonstration->title->{$lang}?>
       </a>
       <?php endif;?>
    </li>
   <?php endforeach;?>
    </ul>
   </li>
  <!-- language switcher -->

  <li>
    <a id ="#language_switcher" href="#language_switcher">
       <img src="<?=IMAGES_URL?>/<?=$lang?>.png" title="<?=$language['language'][$lang]?>" alt="<?=$language['language'][$lang]?>">
       <span style="margin-left:0.3em;"><?=$language['language'][$lang]?></span>
    </a>
    <ul class="sub-menu"> 
     <?php foreach($language['language'] as $key => $value):?>
     <?php if ($key !== $lang): ?>
       <li>
       <a href="<?=$language['url_language'][$key]?>"  lang="<?=$key?>">
       <img src="<?=IMAGES_URL?>/<?=$key?>.png"> <?=$value?></span></a>
       </li>
     <?php endif;?>
     <?php endforeach;?>
  </ul>
</div>