<!DOCTYPE html>
<html>
<head>
<?php include_once TEMPLATE_DIR.'/meta.phtml'?>

    <style>
    body, html {
        height: 100%;
        background:#fff;
        margin:0;
        padding:0;
        font-size:16px;
    }
   
    #header{
       /* background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;*/
        background:#fff;
        padding: 10px 50px;
        box-shadow:  0 0 2px 1px #282a2d; 
    }
    #header ul{
    	list-style-type: none;
    }
    #header ul li{
       display: inline-block;
       margin-right: 10px;
    }
   
    #header > div{
        padding:10px 30px;display:inline;max-height:100%;padding-left:10%;"
    }
   

    a{
    color: #754a15;
    text-decoration:none;
    }
    a:hover{
        color: #8c0209;
    }
    @media screen and (max-width: 700px){
         .site-branding .description{
            font-size:2em;
         }
         #slide7 .description{
          font-size:1.5em;
         }
    }
    @media screen and (max-width: 500px){
         .site-branding .description{
            font-size:2em;
         }
         #slide7 .description{
            font-size:1.5em;
         }
    }
    .content {
      margin-top:30px;
    }
    div.demonstration {
      width:90%;
    }
    </style>
  </head>
  <body > 
  <div id="header">
   <?php include_once TEMPLATE_DIR . '/header.phtml';?>
  </div>
  <div class="content">
   <?php include $content;?>
  </div>
   <?php include_once TEMPLATE_DIR . "/foot.phtml";?>
    <script type="text/javascript">
    window.onbeforeunload = function () {
    	  window.scrollTo(0, 0);
    	}
 </script>
  </body>
</html>