<?php 
include_once INCLUDE_DIR . "/language.php";
$demo = $data->demonstrations[$article_index];
$language = array_merge($language, array("title" => (array)$demo->title));
$content = CONTENT_DIR . "/".$article_name. ".phtml";


?><!DOCTYPE html>
<html>
<head>
<?php include_once TEMPLATE_DIR.'/meta.phtml'?>

    <style>
    body, html {
        height: 100%;
        background:#fff;
        margin:0;
        padding:0;
        font-size:16px;
    }
   

    a{
    color: #754a15;
    text-decoration:none;
    }
    a:hover{
        color: #8c0209;
    }
   
    @media screen and (max-width: 700px){
         .site-branding .description{
            font-size:2em;
         }
         #slide7 .description{
          font-size:1.5em;
         }
    }
    @media screen and (max-width: 500px){
         .site-branding .description{
            font-size:2em;
         }
         #slide7 .description{
            font-size:1.5em;
         }
    }
    .content {
      margin-top:30px;
    }
    div.demonstration {
      width:90%;
    }
    </style>
  </head>
  <body > 
  <div id="header">
   <?php include_once TEMPLATE_DIR . '/header.phtml';?>
  </div>
  <div class="content">
   <?php include $content;?>
  </div>
   <?php include_once TEMPLATE_DIR . "/foot.phtml";?>
    <script type="text/javascript">
    window.onbeforeunload = function () {
    	  window.scrollTo(0, 0);
    	}
 </script>
  </body>
</html>