
<title><?php printer( "title");?></title>
    <meta charset="UTF-8">
    <meta name="robots" content="noindex, nofollow">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<meta property="og:title" content="<?php printer("title");?>" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="http://demo.poleterresolide.fr" />
	<meta property="og:image" content="http://demo.poleterresolide.fr/images/logo-formater-transparent.png" />
    <meta property="og:description" content="<?php printer("presentation1");?>" />
    <meta property="og:locale" content="<?php printer("locale");?>" />
	<meta property="og:locale:alternate" content="<?php printer("alternate");?>" />
	<link href="images/formater_favicon-40x40.png" rel="icon" sizes="32x32">
	<style>
	div.content{
	  margin-bottom: 100px;
	}
	div.partenaire {
	    clear: both;
	    position: relative;
	    z-index: 10;
	    height: 70px;
	    margin-top: 30px;
    }
	div.partenaire div{
	     display:inline-block;
	     height:40px;
	     margin: 0 8px;
	}
	div.partenaire div a{
	     vertical-align:top;
	     opacity:0.9
	}
	div.partenaire div a:hover{
	     opacity:1;
	}
    a{
    color: #754a15;
    text-decoration:none;
    }
    a:hover{
        color: #8c0209;
    }
	</style>