
<title><?php printer( "title");?></title>
    <meta charset="UTF-8">
    <meta name="robots" content="noindex, nofollow">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<meta property="og:title" content="<?php printer("title");?>" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="http://demo.poleterresolide.fr" />
	<meta property="og:image" content="http://demo.poleterresolide.fr/images/logo-formater-transparent.png" />
    <meta property="og:description" content="<?php printer("presentation1");?>" />
    <meta property="og:locale" content="<?php printer("locale");?>" />
	<meta property="og:locale:alternate" content="<?php printer("alternate");?>" />
	<link href="images/formater_favicon-40x40.png" rel="icon" sizes="32x32">
	<style>
	#header{
       /* background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;*/
        background:#fff;
        /* padding: 10px 50px;*/
        height:15%;
        box-shadow:  0 0 2px 1px #282a2d; 
    }
    #header ul{
    	list-style-type: none;
    }
    #header ul li{
       display: inline-block;
       margin-right: 10px;
    }
   
    #header > div{
        padding:10px 30px;display:inline;max-height:100%;padding-left:10%;"
    }
	div.content{
	   margin-bottom: 100px;
	}
	div.partenaire {
        clear: both;
        position: relative;
        z-index: 10;
        height: 70px;
        margin-top: 30px;
    }
	div.partenaire div{
	     display:inline-block;
	     height:40px;
	     margin: 0 8px;
	}
	div.partenaire div a{
	     vertical-align:top;
	     opacity:0.9
	}
	div.partenaire div a:hover{
	     opacity:1;
	}
    a{
        color: #754a15;
        text-decoration:none;
    }
    a:hover{
        color: #8c0209;
    }
    #header li,
    #slide2 li{
        padding:0px;
    }
    #header li a:hover,
    #slide2 li a:hover{
        color:#9d0000;
        font-size:1.01rem;
    }
    ul.sub-menu {
        position:absolute;
        padding:5px 0 0 0;
        max-width:150px;
        display:none;
        margin: 0;
        background:white;
        z-index:2000;
        border: 1px dotted grey;
    }
    li:hover > ul.sub-menu {
        display:block;
        height:auto;
    }
    #header ul.sub-menu li,
    #slide2 ul.sub-menu li{
        float: left;
        position: relative;
        padding: 3px 3px 3px 8px;
        margin-left:0;
        line-height:1;
        text-align: left;
    }
    li.menu-demo ul{
        box-sizing: border-box;
        min-width: 213px;
    }
    li.menu-demo{
        min-width:200px;
    }
    li.menu-demo li{
        min-width:200px;
    }
    .menu-demo li:hover{
        padding-left:12px;
        -webkit-transition: padding 1s ease; /* Safari */
        transition: padding 1s ease;
    }
    #header div.logo img{
      max-height: 95%;
      height:70px;
      margin-top:10px;
     }
     @media screen and (max-width:1150px){
      #header > div {
       padding: 5px;
       }
       #header div.logo img{
          height:50px;
       }
       li.menu-demo{
          max-width:130px;
          min-width:130px;
          overflow:visible;
       }
    }
    
	</style>